version: '3'

services:
  ############################
  # Setup the Apache container
  ############################
  web:
    container_name: apache_webpack
    image: httpd:2.4.38
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/usr/local/apache2/htdocs
      - ./.docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./.docker/apache/vhosts/:/usr/local/apache2/conf/vhosts
    
  #########################
  # Setup the PHP container
  #########################
  php:
    container_name: php_webpack
    build: ./.docker/php/
    volumes:
      - ./app/public:/var/www/html

  ############################
  # Setup the Browsersync container
  ############################
  webpack:
    container_name: webpack
    build: ./.docker/node
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./app:/app